# The default configuration file.
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:5011}
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
  auth:
    enabled: false

data:
  local_data_folder: source_documents

embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: simple

vectorstore:
  database: chroma
  source_type: html

openai:
  api_key: ${OPENAI_API_KEY:}
  model: gpt-3.5-turbo
