predefined_skills = {
    "algorithms": ["algorithms"],
    "javascript": ["javascript", "js"],
    "html": ["html"],
    "sql": ["sql"],
    "css": ["css"],
    "programming": ["programming"],
    "cpp": ["c++", "cpp"],
    "react": ["react", "reactjs"],
    "node.js": ["node.js", "nodejs"],
    "python": ["python"],
    "java": ["java"],
    "data structures": ["data structures", "data structure"],
    "restful apis": ["restful apis", "rest apis", "rest"],
    "git": ["git"],
    "docker": ["docker"],
    "kubernetes": ["kubernetes"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure", "microsoft azure"],
    "continuous integration": ["continuous integration", "ci"],
    "continuous deployment": ["continuous deployment", "cd"],
    "microservices": ["microservices", "micro-service", "microservices architecture"],
    "linux": ["linux"],
    "networking": ["networking"],
    "security": ["security", "cybersecurity"],
    "machine learning": ["machine learning", "ml"],
    "data analysis": ["data analysis", "data analytics"],
    "typescript": ["typescript", "ts"],
    "vue.js": ["vue.js", "vuejs", "vue"],
    "angular": ["angular", "angularjs"],
    "swift": ["swift"],
    "kotlin": ["kotlin"],
    "ruby": ["ruby"],
    "ruby on rails": ["ruby on rails", "rails"],
    "php": ["php"],
    "laravel": ["laravel"],
    "django": ["django"],
    "flask": ["flask"],
    "spring": ["spring", "spring boot"],
    "go": ["go", "golang"],
    "scala": ["scala"],
    "haskell": ["haskell"],
    "elixir": ["elixir"],
    "shell scripting": ["shell scripting", "bash", "sh"],
    "powershell": ["powershell"],
    "ansible": ["ansible"],
    "terraform": ["terraform"],
    "jenkins": ["jenkins"],
    "circleci": ["circleci"],
    "travisci": ["travisci"],
    "splunk": ["splunk"],
    "elk stack": ["elk stack", "elasticsearch", "logstash", "kibana"],
    "grafana": ["grafana"],
    "prometheus": ["prometheus"],
    "puppet": ["puppet"],
    "chef": ["chef"],
    "r": ["r"],
    "sas": ["sas"],
    "tableau": ["tableau"],
    "power bi": ["power bi", "powerbi"],
    "bigquery": ["bigquery"],
    "hadoop": ["hadoop"],
    "spark": ["spark"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "tensorflow": ["tensorflow"],
    "pytorch": ["pytorch"],
    "matlab": ["matlab"],
    "opencv": ["opencv"],
    "airflow": ["airflow"],
    "kafka": ["kafka"],
    "rabbitmq": ["rabbitmq"],
    "grpc": ["grpc"],
    "protobuf": ["protobuf"],
    "blockchain": ["blockchain"],
    "ethereum": ["ethereum"],
    "solidity": ["solidity"],
    "truffle": ["truffle"],
    "web3.js": ["web3.js", "web3"],
    "three.js": ["three.js", "threejs"],
    "unity": ["unity"],
    "unreal engine": ["unreal engine", "unreal"],
    "godot": ["godot"],
    "blender": ["blender"],
    "3ds max": ["3ds max", "3dsmax"],
    "maya": ["maya"],
    "cinema 4d": ["cinema 4d", "cinema4d"],
    "photoshop": ["photoshop"],
    "illustrator": ["illustrator"],
    "xd": ["xd", "adobe xd"],
    "figma": ["figma"],
    "sketch": ["sketch"],
    "invision": ["invision"],
    "zeplin": ["zeplin"],
    "mongodb": ["mongodb"],
    "postgresql": ["postgresql", "postgres"],
    "mysql": ["mysql"],
    "sqlite": ["sqlite"],
    "redis": ["redis"],
    "cassandra": ["cassandra"],
    "couchdb": ["couchdb"],
    "dynamodb": ["dynamodb"],
    "realm": ["realm"],
    "firebase": ["firebase"],
    "heroku": ["heroku"],
    "netlify": ["netlify"],
    "vercel": ["vercel"],
    "digitalocean": ["digitalocean"],
    "linode": ["linode"],
    "openstack": ["openstack"],
    "vmware": ["vmware"],
    "hyper-v": ["hyper-v"],
    "virtualbox": ["virtualbox"],
    "vagrant": ["vagrant"],
    "salesforce": ["salesforce"],
    "sap": ["sap"],
    "oracle": ["oracle"],
    "workday": ["workday"],
    "servicenow": ["servicenow"],
    "jira": ["jira"],
    "confluence": ["confluence"],
    "microsoft teams": ["microsoft teams", "teams"],
    "slack": ["slack"],
    "zoom": ["zoom"],
    "google meet": ["google meet", "meet"],
    "webex": ["webex"],
    "trello": ["trello"],
    "asana": ["asana"],
    "notion": ["notion"],
    "monday.com": ["monday.com", "monday"],
    "basecamp": ["basecamp"]
}

alias_to_skill = {}
for skill, aliases in predefined_skills.items():
    for alias in aliases:
        alias_to_skill[alias.lower()] = skill

def get_matched_skills(resume_skills):
    matched_skills = set()
    for skill in resume_skills:
        lower_skill = skill.lower()
        if lower_skill in alias_to_skill:
            matched_skills.add(alias_to_skill[lower_skill])
    return list(matched_skills)
